Базовая стилизация всех страниц
htmlacademy-htmlcss/2279363-sedona-36 pull request #5
Opened 2023-02-14 21:35 UTC by PetrovaAleksandra

Андрей, перечислю проблемы с которыми я столкнулась и не понимаю как их решить:
1. Хочу сюда. за дала text-transform: uppercase; , на главной странице работает, а на каталоге - нет. Почему? Ведь шапка и футер одинаковые на весь сайт.
Та же проблема с иконками в футере. и не только с иконками.
2. Сначала растянула фотки в формате 100% auto, все работала, но потом Николай Шабалин где то обмолвился, что так делать пока не надо, прописываем размеры фоновых фото - результат печальный, смотрю и ужасаюсь.
3. Текст наезжает на фото. очень раздражает, но полагаю, что до оформления сеток это норма, так?
4. visually-hidden где-то работает, а где-то не хочет. почему??? Все делаю одинаково. Что за черная магия?
5. Фото в блоке подписки вообще обрезается. почему даже боюсь предположить, ведь другие фото криво, но стоят целиком? Тоже похоже на черную магию.
6. точки и подчеркивания из списков в каталоге убрала - а они не убираются?
Вывод: я бездарность, но очень хочу перестать ею быть))))
Еще раз спасибо за терпение! Как проснусь завтра, как поправлю все, как начнете Вы мной гордиться)))

---
:mortar_board: [Базовая стилизация всех страниц](https://up.htmlacademy.ru/htmlcss/36/user/2279363/tasks/8)

:boom: https://htmlacademy-htmlcss.github.io/2279363-sedona-36/5/

2023-02-15 16:55 UTC, andreysgra requested changes
1. Свойство `text-transform: uppercase` использовано в классе `.navigation-link-want-here`. Этот класс на главной странице применён к ссылке, а на странице каталога нет.
2. Пусть пока будет так, как есть.
3. Да, конечно. При чём даже не в следующем разделе, а в разделах 6, 7 всё станет на свои места.
4. А хотелось бы узнать, где работает? :smirk: У вас же ещё нет стилей для этого класса (в этом задании про них не рассказывается). Это не какой-то встроенный класс который вот так вот только одним названием скрывает элемент, для него нужен набор стилей. А класс мог бы называть и по другому, просто у нас так принято его называть.
5. Ну а как ещё может быть, если у вас пока не определены размеры контентной области? Ширина контентной области этого проекта равна 1200px, если измерить в макете, соответственно и фоновые изображения имеют такую же ширину. А ширина видимой части окна браузера, как правило больше этого значения и зависит от разрешения монитора пользователя. Вообще не переживайте по поводу несоответстия макету. Вёрстка начнёт становиться более-менее похожей на макет уже после шестого раздела.
6. Почему? Не вижу точек в списках, а вот подчёркивание (оно возникает только в ссылках) нужно непосредственно убирать у ссылки, а не в самом списке, так как это свойство не наследуется.

Ну а на счёт своего вывода вы сильно преувеличиваете. Всё идёт по плану и не стоит сильно переживать и недооценивать себя.

2023-02-15 16:55 UTC, andreysgra commented on catalog.html
> +                <a class="breadcrumbs-hotel" href="catalog.html">Гостиницы</a>
Несмотря на то, что первая ссылка ведущая на главную странице отличается от остальных ссылок, стоит всем ссылкам присвоить один класс, ну и класс должен отражать предназначение элемента. Это ссылки в списке "хлебные крошки", так что логичнее назвать класс `breadcrumbs-link`. Позже, в следующих заданиях, когда будете оформлять эти элементы, добавите первой ссылке дополнительный класс, чтобы показать изображение домика.

А такое именование, которое конкретно указывает на название пункта меню, крайне неудачное. Здесь всего лишь пример "хлебных крошек" и пунктов меню может быть несколько, а также на разных страницах они будут совершенно другие. Например, как на этом сайте:
![image](https://user-images.githubusercontent.com/17790771/219079913-f02f393a-272d-4789-a736-ffdab6193fed.png)

2023-02-15 16:55 UTC, andreysgra commented on catalog.html
> +              <input class="" type="radio" name="infrastructure" value="swimming-pool" checked>Бассейн
Если класса нет, то атрибут `class` с пустым значением нужно удалить.

2023-02-15 16:55 UTC, andreysgra commented on catalog.html
> +            <p class="filter-hotel-price">Стоимость, ₽:</p>
В макете мы видим, что надписи "Инфраструктура", "Тип Жилья", "Стоимость, ₽" оформлены одинаково, да и находятся в одном блоке - в форме. Поэтому вполне логично, что для оформления этих надписей нужно использовать один класс, а не три разных.

2023-02-15 16:55 UTC, andreysgra commented on catalog.html
>                      <h3 class="product-card-title">Amara Resort & Spa</h3>
А вот здесь для совершенно разных HTML элементов вы используете одинаковый класс `product-card-title`. Это нехорошо хотя бы той причине, что у ссылки одни браузерные свойства, которые нужно отменить, например `text-decoration: none`, но таковых свойств у `h3` и в помине нет, а зато у `h3` есть предустановленные значения свойства `margin`, которых нет у ссылки.

Для ссылки логичнее в названии указывать, что это ссылка `product-card-link`.

2023-02-15 16:55 UTC, andreysgra commented on catalog.html
> +            <a href="#"><span class="pagination-link">1</span></a>
А зачем понадобилось в ссылках текст оборачивать в `span`? Есть такой критерий [HTML-06](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06) и он базовый, а значит проект защиту не пройдёт.

Ну и кроме того класс `pagination-link` нужно отдать ссылке, ведь его название говорит само за себя "ссылка нумерации страниц".

2023-02-15 16:55 UTC, andreysgra commented on index.html
> +            <h3 class="advantages-devil-bridge">Там есть мост дьявола</h3>
Опять же, тексты в `h3` одинаково оформлены (есть небольшой нюанс с цвете текста у 1 и 5 пунктов списка), а вы им даёте различные классы. Вот это избыточность, которой нужно избегать. Представьте, что это список не из пяти пунктов, а из пятидесяти. Замучаетесь названия классам придумывать 😄 . Было нормальное название `advantages-title`, зачем переделали?

2023-02-15 16:55 UTC, andreysgra commented on index.html
> +          <li class="footer-social-item youtube">
А к чему дополнительные классы, такие как `telegram` элементам списка? Интерактивный элемент не `li`, а ссылка. Не будем забегать вперёд, но фоновые картинки соцсетей нужно удалить, с этой графикой разберёмся в одном из следующих разделов.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  font-display: swap;
А у вас в проекте (в папке `fonts`) есть файлы этих шрифтов? Нет. А зачем вы подключаете то, чего у вас нет?

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  src: url("../fonts/pt-sans-bold.woff2") format("woff2");
Зайдите в папку fonts и посмотрите на название файлов шрифтов. Они называются совсем не так. А поскольку вы указываете неправильный путь к файлам, то шрифты к браузеру не подключаются. Это несложно узнать исследовав какой-нибудь элемент с текстом:
![image](https://user-images.githubusercontent.com/17790771/219088193-7a47a863-e0aa-402e-a962-80df9e38f475.png)
Браузер не нашёл нужный шрифт и использовал вместо него Arial.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +.main-header {
В критерии [PROJ-01](https://up.htmlacademy.ru/htmlcss/36/criteries#PROJ-01) есть ссылка на [кодгайд Академии](http://codeguide.academy/html-css.html). Это базовый критерий, то есть он важен для успешной защиты. Внимательно изучите, как нужно оформлять код. Я не буду ничего подробно расписывать, там всё есть. В данном случае претензия к отступам между блоками правил.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Я уже упоминал, что свойство `font-family` наследуемое, то есть передаётся от родительского элемента. Так как в седоне кроме PT Sans не используется другое семейство шрифтов, то его достаточно указать в `body`. Есть небольшие исключения для элементов форм и `button`, там нужно явно указывать это значение.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  background-image: url("../images/main/red-rocks.jpg");
А вот это фоновое изображение нужно применить к блоку `hero-text-container`, а не к `main-index`.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +}
Я уже предупреждал, что в данном задании никакие геометрические размеры мы не задаём, так как это предмет следующих заданий, а сейчас указав их неверно в дальнейшем придётся их править, что усложнит вам работу.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  background-color: #82B3D3;
[PROJ-01](https://up.htmlacademy.ru/htmlcss/36/criteries#PROJ-01)

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +.advantages-devil-bridge {
Про название классов написал в комментарии к index.html.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +}
Всё это смело можно выкинуть (смотрите мой комментарий по разметке).

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  background-image: url("../images/catalog/blured-rocks-catalog.jpg");
Фон не нужно вешать на всю контентную область (это в макете барбершоп можно, но там дизайн иной). Соответственно и `background-color` области не нужен.

2023-02-15 16:55 UTC, andreysgra commented on catalog.html
>              <form class="filter-hotel" action="https://echo.htmlacademy.ru/" method="get">
А вот форму нужно вытащить из этой секции. Как мы видим
![image](https://user-images.githubusercontent.com/17790771/219097440-14a11349-88c8-4e27-abb3-daf1957e9212.png)
заголовок страницы, хлебные крошки и форма поиска гостиницы находятся в одном блоке с фоном. Фон нужно навесить на этот блок, а не на `main`.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +.filter-hotel-infrastructure {
Про общий класс писал в комментарии к catalog.html.

2023-02-15 16:55 UTC, andreysgra commented on styles/styles.css
> +  text-decoration: none;
Свойство `text-decoration` нужно применить к ссылке, а не списку.

2023-02-16 12:08 UTC, PetrovaAleksandra commented on catalog.html
> +                <a class="breadcrumbs-hotel" href="catalog.html">Гостиницы</a>
verstehen

2023-02-16 12:48 UTC, PetrovaAleksandra commented on catalog.html
>                      <h3 class="product-card-title">Amara Resort & Spa</h3>
Тогда ссылке с фото задала другой класс product-card-gallery

2023-02-16 12:50 UTC, PetrovaAleksandra commented on catalog.html
> +            <a href="#"><span class="pagination-link">1</span></a>
у меня почему-то подчеркивание не работала, пока в спан не обернула и задала класс спану. Сейча спопробую разобраться

2023-02-17 09:37 UTC, PetrovaAleksandra commented on index.html
> +            <h3 class="advantages-devil-bridge">Там есть мост дьявола</h3>
так дяденька сказал))) на лайве

2023-02-18 06:40 UTC, andreysgra commented on index.html
> +            <h3 class="advantages-devil-bridge">Там есть мост дьявола</h3>
Либо вы что-то не так поняли, либо дяденька так сказал. А вообще это не аргумент - "кто-то сказал". Я своё замечание пояснил, почему так делать не следует.

2023-02-18 10:38 UTC, PetrovaAleksandra commented on index.html
> +            <h3 class="advantages-devil-bridge">Там есть мост дьявола</h3>
Я поставила им 2 класса. title, чтобы шрифты поставить и потом когда буду цветные блоки делать - буду им разные цвета делать, ориентируясь на разные классы, хотя мне кажется проще было оставит разные классы и как было у меня перечислить их, когда у них общие свойства и отдельным прописать когда свойства по цветам разные. Не согласны?

2023-02-18 10:44 UTC, PetrovaAleksandra commented on styles/styles.css
> +  font-display: swap;
Что-то да... я просто вспомнила, что там цитаты так надо прописывать, думаю, ну на будущее))) сори, убираю

2023-02-18 11:06 UTC, PetrovaAleksandra commented on styles/styles.css
> +  background-image: url("../images/main/red-rocks.jpg");
Тогда и фон тоже, получается, раз фон замена не загрузившейся картинки?

2023-02-18 12:07 UTC, andreysgra commented on styles/styles.css
> +  background-image: url("../images/main/red-rocks.jpg");
Да, и фоновый цвет тоже.

2023-02-18 17:38 UTC, andreysgra commented on index.html
> +            <h3 class="advantages-devil-bridge">Там есть мост дьявола</h3>
Нет, не согласен.

Ещё раз смотрим в макете этот блок:
![image](https://user-images.githubusercontent.com/17790771/219879694-02118521-a613-4345-be34-c5b8c8c08323.png)
Мы видим, что начертание текста заголовка во всех пяти элементах одинаково, единственное отличие - цвет текста в первом и пятом элементе.

Вот вы описали все текстовые свойства в классе `.advantages-subtitle`. Скажите, а какие свойства будут в классах `.advantages-small-area, .advantages-beautiful-road, .advantages-few-tourists`? Там даже цвет одинаковый.

Дополнительный класс нужен только первому и пятому элементу, чтобы в нём описать белый цвет текста, но при этом класс должен быть общим для них, а не два разных класса `.advantages-real-town, .advantages-devil-bridge`.

Да и вообще здесь можно обойтись без классов для этих заголовков (просто поясняю, но не обязательно переделывать). У элемента списка есть класс `.advantages-item`, заголовок `h3` в этом элементе является дочерним по отношению к `.advantages-item`, а значит мы можем написать такой селектор `.advantages-item h3` и в нём описать все необходимые свойства. Помните, я говорил, что первому и пятому элементу потребуется дополнительный класс - у них и геометрия другая, и цвет фона. Чтобы как-то подчеркнуть эти особенности дополнительный класс можно назвать `.advantages-item-with-image`. И тогда у 1-го и 5-го `li` в разметке будет 2 класса: `advantages-item advantages-item-with-image`. Чтобы изменить цвет текста заголовка с белого на чёрный нужно изменить свойство `color` в таком вот селекторе `.advantages-item-with-image h3`. И, как видите, нам не потребовались классы ни к одному заголовку в этом списке. А вы написали аж целых пять классов!

2023-02-18 19:34 UTC, merged

2023-02-19 11:53 UTC, PetrovaAleksandra commented on index.html
> +            <h3 class="advantages-devil-bridge">Там есть мост дьявола</h3>
Как научили - так и делаю )))) Нам предложили такую реализацию и сказали, что так практикуют в лиге. Стараются давать максимум уникальных классов, чтобы потом их было просто обьединять в сss по похожему дизайну. например 1и 5 блок, 2 и 4 блок фон одного цвета, а 3 блок вообще третий цвет фона. как то так. Какие же вы противоречивые между собой))) Спасибо, эту логику я тоже поняла, хотя, с разными классами мне кажется проще и удобней просто потому что я уже успела ее принять и уложить ее в своей голове.

2023-02-19 11:55 UTC, PetrovaAleksandra commented on styles/styles.css
> +  background-color: #82B3D3;
оу, про регистр букв вообще не уловила. спасибо

2023-02-19 11:55 UTC, PetrovaAleksandra commented on styles/styles.css
> +  background-color: #82B3D3;
скопировала с фигмы слепо