Флексы
htmlacademy-htmlcss/2279363-sedona-36 pull request #6
Opened 2023-02-28 21:59 UTC by PetrovaAleksandra

Андрей, добрый день!
С какими вопросами я еще столкнулась.
На странице каталога в шапке установила паддинги, но они не работают. торчит фон из под фото, текст уехал.
Футер должен быть одинаковым на страницах, но на главной он подчеркнут. как так? ума не приложу.
Навигация уехала от логотипа в шапке. полагаю, это в следующем разделе править?
пошла читать следующий блок

2023-03-01 18:32 UTC, andreysgra requested changes
Ответы на ваши вопросы:
> На странице каталога в шапке установила паддинги, но они не работают. торчит фон из под фото, текст уехал.

Потому что высота блока превышает высоту изображения, а так как вы значение `background-size` задали явно, то изображение не растягивается:
![image](https://user-images.githubusercontent.com/17790771/222231150-43be0755-7fcd-4058-96af-a9636a9fc3c6.png)
Этому свойству можно задавать и другие, предопределённые значения и изображение будет вести себя в зависимости от них.

> Футер должен быть одинаковым на страницах, но на главной он подчеркнут. как так?

Футер на всех страницах одинаков, где вы увидели подчёркивание, не понимаю.

> Навигация уехала от логотипа в шапке

Об этом написал в комментарии к навигации.

2023-03-01 18:32 UTC, andreysgra commented on index.html
> +            <p class="contacts-phone" href="tel:+78128121212">+7 (812) 812-12-12</p>
А зачем текст ссылки нужно помещать в параграф? До этого всё было правильно размечено.

2023-03-01 18:32 UTC, andreysgra commented on catalog.html
> +    </div>
Этот тег `</div>` должен идти после `</footer>, а на его месте должен стоять тег `</main>`. Проверьте валидацию HTML.

2023-03-01 18:32 UTC, andreysgra commented on catalog.html
> +        <div class="page-container">
А этот тег к чему здесь?

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
Причина, почему ссылка "хочу сюда" вышла за пределы контейнера
![image](https://user-images.githubusercontent.com/17790771/222218015-5cf8689f-bbef-439a-bf85-e6bab1d4a175.png)
Ширина общего контейнера равна 1200px. Хэдер `.main-header` имеет паддинги по 70px, то есть доступная ширина для дочерних элементов равна 1200 - 70 * 2. А вы зачем-то явно задали ширину `navigation`, которая превышает свободное пространство внутри `.main-header`.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +.catalog-container {
Чем контейнер `.catalog-container` отличается от `.index-container`. Вам не кажется, что нужен один класс для всех страниц сайта, который у вас уже есть, но вы его не используете (`.page-container`)?

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +.index-container {
Стоит переименовать в `.container`.

2023-03-01 18:32 UTC, andreysgra commented on catalog.html
> +    <div class="catalog-container">
```suggestion
    <div class="page-container">
```

2023-03-01 18:32 UTC, andreysgra commented on index.html
> +    <div class="index-container">
```suggestion
    <div class="page-container">
```

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  justify-content: space-between;
Свойство `justify-content` перераспределяет свободное пространство внутри flex контейнера, а так как в этом контейнера свободного пространства нет, то и свойство это без надобности ему.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  justify-content: center;
В этом flex контейнере свойство `justify-content` тоже без надобности.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  align-items: center;
А вот текст лучше подвинуть на нужное расстояние с помощью паддингов, не факт, что текст в макете располагается точно по центру.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  padding: 0;
У тега `li` таких свойств по умолчанию нет, так что не нужно сбрасывать то, чего нет изначально.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  width: 1200px;
Ширина уже определена глобальным контейнером `.page-container`, зачем её указывать явно? Это может сыграть такую же злую штуку, как в навигации.

По умолчанию блок занимает всю доступную ширину родителя. Если у родительского блока ширина 1200px, то и дочерний блок будет такой же ширины.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  justify-content: space-between;
Здесь тоже нет свободного пространства для перераспределения.

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  height: 385px;
```suggestion
  min-height: 385px;
```

2023-03-01 18:32 UTC, andreysgra commented on styles/styles.css
> +  flex-direction: column;
А к чему здесь вообще `flex` контейнер?

2023-03-02 18:07 UTC, PetrovaAleksandra commented on index.html
> +            <p class="contacts-phone" href="tel:+78128121212">+7 (812) 812-12-12</p>
ой, не знаю откуда взялся этот ляп, не заметила, спасибо.

2023-03-02 18:20 UTC, PetrovaAleksandra commented on styles/styles.css
> +  margin: 0 auto;
я переделала на гридах

2023-03-02 18:38 UTC, PetrovaAleksandra commented on styles/styles.css
> +.catalog-container {
Божечки, какой ужас! Это я понаделала? у меня и разметке то .catalog-container нет....

2023-03-02 18:43 UTC, PetrovaAleksandra commented on styles/styles.css
> +.index-container {
сдалала page-container для всех страниц

2023-03-03 07:53 UTC, andreysgra commented on catalog.html
> +        <div class="page-container">
`<div class="page-container">` нужно удалить. Чтобы у вас не было вопроса "почему?" проверьте валидацию HTML этой страницы в [валидаторе](https://validator.w3.org/nu/#textarea).

2023-03-03 07:53 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
А толку от этого?

Хэдер теперь занимает всю доступную ширину страницы
![image](https://user-images.githubusercontent.com/17790771/222662336-2422c00d-66cb-43cc-962c-219d088a9eca.png)
Но он не должен выходить за пределы контейнера, ширина которого равна 1200px.

2023-03-03 07:53 UTC, andreysgra commented on catalog.html
> +    <div class="catalog-container">
А почему не исправили на `page-container`?

2023-03-03 07:53 UTC, andreysgra commented on styles/styles.css
> +.catalog-container {
Ну почему же, есть `catalog-container` на странице каталога.

2023-03-03 07:59 UTC, andreysgra requested changes

2023-03-03 07:59 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
Навигации `.navigation` не нужно задавать ширину, так как ширина уже определена общим контейнером `.page-container`. Также не нужно свойство `margin: 0 auto`.

2023-03-06 17:35 UTC, merged